[tool.poetry]
name = "zero-shot-pentesting-paper"
version = "0.1.0"
description = ""
authors = ["Christophe Genevey-Metat <cgeneveymetat@silicom.fr>"]
readme = "README.md"
packages = [{include = "zero_shot_pentesting_paper"}]

[tool.poetry.dependencies]
python = "^3.10"
nasim = "0.11.0"
transformers = "4.27.4"
gym = "^0.26.2"
torch = "2.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
